title: Hoya012's Research Blog
description: Study Blog with paper reviews.

#url: http://brianmaierjr.github.com/long-haul
url: https://hoya012.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
#gems: [jekyll-paginate]
gems:
 - jekyll-paginate
 - jekyll-archives
paginate: 10

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'
    
# Category descriptions (for archive pages)
descriptions:
  - cat: object detection
    desc: ""

  - cat: classification
    desc: ""

  - cat: etc
    desc: ""

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: hoya012
   #twitter: brianmaierjr
   facebook: 2.hoseong
   email: lee.hoseong@sualab.com

google_analytics: "UA-58263416-1"
