title: Hoya012's Research Blog
description: Study Blog with paper reviews.

#url: http://brianmaierjr.github.com/long-haul
url: https://hoya012.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 10

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: hoya012
   #twitter: brianmaierjr
   facebook: 2.hoseong
   email: lee.hoseong@sualab.com

google_analytics: "UA-58263416-1"
